### ISSUE TITLE
Only errors on clicks

### ISSUE THREAD

**Issue by PeLLmEn** [shamhi/NotCoinBot#1]
The bot was the best till today... Now only errors while trying to click(((

**Comment by shamhi** [comment]
I noticed it too, the problem is being solved

**Comment by PeLLmEn** [comment]
> the problem is being solved

By adding tls bypass?  There's the working one bypass from here: https://github.com/ConfusedCharacter/NotCoin-Cheat/commit/50848d86f9b387a494d67871adaa07702b291bc5

**Comment by shamhi** [comment]
Did you run this code : https://github.com/ConfusedCharacter/NotCoin-Cheat/commit/50848d86f9b387a494d67871adaa07702b291bc5? Is he working?

> > the problem is being solved
> 
> By adding tls bypass? There's the working one bypass from here: [ConfusedCharacter/NotCoin-Cheat@50848d8](https://github.com/ConfusedCharacter/NotCoin-Cheat/commit/50848d86f9b387a494d67871adaa07702b291bc5)
> 
> Or here: https://github.com/Poryaei/NotCoin-Clicker/commits/main/

**Comment by PeLLmEn** [comment]
> Did you run this code :

Yes. I'm running it right now

PS: если что, можно и по-русски

**Comment by PeLLmEn** [comment]
And change please to js2py like explained here - the easiest way - https://github.com/nazavod777/notcoin_bot/issues/1#issuecomment-1885806725

**Comment by shamhi** [comment]
у тебя выкинуло с аккаунта тг после использования скрипта [ConfusedCharacter/NotCoin-Cheat@50848d8](https://github.com/ConfusedCharacter/NotCoin-Cheat/commit/50848d86f9b387a494d67871adaa07702b291bc5) ?

**Comment by PeLLmEn** [comment]
> у тебя выкинуло с аккаунта тг после использования скрипта [ConfusedCharacter/NotCoin-Cheat@50848d8](https://github.com/ConfusedCharacter/NotCoin-Cheat/commit/50848d86f9b387a494d67871adaa07702b291bc5) ?

Нет, все прекрасно работает, ничего не выкидывало ни разу

**Comment by shamhi** [comment]
> > у тебя выкинуло с аккаунта тг после использования скрипта [ConfusedCharacter/NotCoin-Cheat@50848d8](https://github.com/ConfusedCharacter/NotCoin-Cheat/commit/50848d86f9b387a494d67871adaa07702b291bc5) ?
> 
> Нет, все прекрасно работает, ничего не выкидывало ни разу. 3 акка им кручу и ни на одном нет косяков. Все аккаунты на месте как на андроиде, так и на айфоне

не пойму почему, но при первом же запуске выкинуло с аккаунта со всех устройств
https://github.com/nazavod777/notcoin_bot/issues/5#issuecomment-1897781251 тут у чела такая же история

**Comment by PeLLmEn** [comment]
> не пойму почему, но при первом же запуске выкинуло с аккаунта со всех устройств и зайти обратно не могу, код на номер не приходит

А ты вшил обход и на своём боте пробуешь?

**Comment by shamhi** [comment]
> > не пойму почему, но при первом же запуске выкинуло с аккаунта со всех устройств и зайти обратно не могу, код на номер не приходит
> 
> А ты вшил обход и на своём боте пробуешь?

нет, я для теста скопировал весь код и, ничего не поменяв, запустил
как обычно ввел id, hash, номер и код, который прислал тг, и через пару секунд вышла ошибка, и с аккаунта вылетело на всех устройствах

**Comment by PeLLmEn** [comment]
Ты про этот бот говоришь? https://github.com/ConfusedCharacter/Notcoin-Cheat

**Comment by shamhi** [comment]
> Ты про этот бот говоришь? https://github.com/ConfusedCharacter/Notcoin-Cheat

да

**Comment by PeLLmEn** [comment]
Странно. Ща он майнит мне, правда дома телефон с termux лежит. Все аккаунты работают и майнинг идет

**Comment by shamhi** [comment]
я тоже не могу понять, один чел пишет что причина в телетоне

сейчас вообще флудвейт дали на сутки за большое количество попыток входа, уже в поддержку написал, не отвечают

**Comment by PeLLmEn** [comment]
А своего бота не пробовал пока менять?

**Comment by shamhi** [comment]
бот заработал на другом аккаунте когда я поменял телетон на пирограм



> А своего бота не пробовал пока менять?

да, я пытаюсь перенести TLS обход с requests на aiohttp

**Comment by shamhi** [comment]
Бот работает
