### ISSUE TITLE
wrong method

### ISSUE THREAD

**Issue by shahrooz1397** [shamhi/NotCoinBot#15]
13:50:39 | ERROR    | 120 - my_Session | Неизвестная ошибка при авторизации: Telegram says: [400 BOT_METHOD_INVALID] - The method can't be used by bots (caused by "messages.RequestWebView")

**Comment by shahrooz1397** [comment]
should i use phone number instead of token?
i wish the russian text's was in english

**Comment by shamhi** [comment]
> should i use phone number instead of token?

yes

> i wish the russian text's was in english
there's no such method yet, use translator
