### ISSUE TITLE
not respond

### ISSUE THREAD

**Issue by arm4xlll** [shamhi/NotCoinBot#18]
запускаю, пишет что запустился и дальше ниче не происходит (и на 2 и на 3 режиме)
че я не так мог сделать

**Comment by shamhi** [comment]
не может быть так, что ничего не происходит

**Comment by arm4xlll** [comment]
в том то и дело что ошибок никаких нет, он просто начинает и молчит. Это скорее с моим апи что то не так, оно нигде не работает, никаких ошибок, вообще ничего. Я с чистого аккаунта пробовал и результат тот же. Как это фиксить?

**Comment by shamhi** [comment]
оно походу не может подключиться к твоему аккаунту, попробуй сменить API_ID и API_HASH, возможно поможет

**Comment by arm4xlll** [comment]
как его сменить то

**Comment by shamhi** [comment]
в settings.json

**Comment by arm4xlll** [comment]
короче я разобрался, проблема была в рассинхроне времени (у меня на 4 минуты время отставало пиздец) щас все ок
