### ISSUE TITLE
api access denied

### ISSUE THREAD

**Issue by THMaST3R** [shamhi/NotCoinBot#19]
21:56:31 | INFO     | 85 - Бот запущен без возможности управления через телеграмм 

21:56:32 | WARNING  | 383 - master | Доступ к API запрещен: 403
21:56:32 | INFO     | 384 - master | Сплю 5 сек

**Comment by shamhi** [comment]
try with proxy or vpn

**Comment by THMaST3R** [comment]
I used vpn, vps and proxy, but none of them worked
