### ISSUE TITLE
Доступ к API запрещён.

### ISSUE THREAD

**Issue by PeLLmEn** [shamhi/NotCoinBot#2]
Что-то у меня все равно не завелся(((
![IMG_20240120_002055](https://github.com/shamhi/NotCoinBot/assets/36919324/560cc91a-d42f-4b37-859e-d19b3359b4cc)

При том в другом боте при старте примерно та же проблема, но после 4-5 раза пускает и начинает майнит, но там кд не 60сек, а секунд 10. 
Жду пока, может заведётся после какой-нибудь попытки. 
Ещё попробую другой API, хотя на этом другой бот норм отрабатывает. 

UPD1: заработало, однако только на двух акках из трех почему-то

UPD2: майнит, но заставить майнить три акка не вышло - майнит два, а один из них (рандомно) не получает доступ апи. + нарвался на то, что бот майнил, а в итоге снова с ошибкой апи выскочил на акке, на котором до этого майнил. Можно в этом боте посмотреть, как он генирирует новый Auth, возможно именно в этом проблема кроется - https://github.com/Poryaei/Notcoin-Clicker

UPD3: с другим апи та же история...

UPD4: думал от времени апи станет доступен - нет. Перезапуска бота начинают работать рандомно то два акка, то один, то все три без доступа.

UPD5: грешу на пакеты, ща устанавливаю все из requirements.txt и проверяю по новой (если не выйдет - попробую обновить, возможно там просто не последние версии пакетов указаны уже для работы с телегой) .

UPD6: перестановка пакетов проблему не решила.

**Comment by shamhi** [comment]
то же самое, то 2 акка работают, то 1, то 0

**Comment by shamhi** [comment]
![Screenshot_73](https://github.com/shamhi/NotCoinBot/assets/148555284/e9738d57-a09e-4845-ab0b-81e6456b09ff)
это на локальном пк

![Screenshot_74](https://github.com/shamhi/NotCoinBot/assets/148555284/312d8ed9-9e34-4812-9604-5647a29cad18)
это на vps

я думаю, что они блокируют IP адреса за большое количество запросов, 3 дня без остановки VPS майнил, и скорее всего IP попал к ник в блоклист, поэтому доступ запрещен

**Comment by PeLLmEn** [comment]
> IP попал к ник в блоклист

А при перезапуске бота разве не становится норм? У меня просто рандомно то есть запрет, то нет

**Comment by shamhi** [comment]
попробуй обновить репозиторий, я там кое-что еще добавил

вроде теперь все работает у меня

**Comment by PeLLmEn** [comment]
> попробуй обновить репозиторий, я там кое-что еще добавил
> 
> вроде теперь все работает у меня

Всё отлично работает)) спасибо огромное!
