### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lok3rn3t** [shamhi/NotCoinBot#20]
File "/var/lib/pufferpanel/servers/dd932c50/bot/utils/launcher.py", line 52, in get_session_string
    if not session:
           ^^^^^^^
UnboundLocalError: cannot access local variable 'session' where it is not associated with a value

**Comment by Lok3rn3t** [comment]
File "/var/lib/pufferpanel/servers/dd932c50/bot/utils/launcher.py", line 60, in get_clients
    raise FileNotFoundError("Not found session files")
FileNotFoundError: Not found session files

**Comment by shamhi** [comment]
you don't have session file in folder sessions/

**Comment by Lok3rn3t** [comment]
> you don't have session file in folder sessions/

it is created and exists, but the program doesn't seem to see it.

**Comment by shamhi** [comment]
update repository and try again
