### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Visualua** [shamhi/NotCoinBot#22]
08:56:51 | ERROR    | 191 - MySession | Не удалось получить список товаров, ответ: {"ok":false,"data":{"message":"\nInvalid `prisma.user.findUnique()` invocation:\n\n\nCan't reach database server at `private-notcoin-ro-ams-mysql-do-user-10957498-0.c.db.ondigitalocean.com`:`25060`\n\nPlease make sure your database server is running at `private-notcoin-ro-ams-mysql-do-user-10957498-0.c.db.ondigitalocean.com`:`25060`.","error":"PrismaClientKnownRequestError","statusCode":500}}
08:57:05 | ERROR    | 300 - MySession  | Неизвестная ошибка при получении статуса бесплатных баффов: string indices must be integers, not 'str', ответ: {"ok":false,"data":{"message":"\nInvalid `prisma.taskXUser.findMany()` invocation:\n\n\nCan't reach database server at `private-notcoin-ro-ams-mysql-do-user-10957498-0.c.db.ondigitalocean.com`:`25060`\n\nPlease make sure your database server is running at `private-notcoin-ro-ams-mysql-do-user-10957498-0.c.db.ondigitalocean.com`:`25060`.","error":"PrismaClientKnownRequestError","statusCode":500}}

**Comment by shamhi** [comment]
Эти ошибки на стороне их сервера
