### ISSUE TITLE
Error Authorization

### ISSUE THREAD

**Issue by xdenotte** [shamhi/NotCoinBot#23]
Пишет неизвестная ошибка при авторизации: no such column: username

**Comment by Visualua** [comment]
> Пишет неизвестная ошибка при авторизации: no such column: username

 Мне помогло пересоздать сессию. Но при этом после запуска её, куча ошибок вылазит, как при попытке отловить бусты для активации, так и в общем при кликах.

**Comment by xdenotte** [comment]
исправил созданием новой сессии

**Comment by xdenotte** [comment]
Вообщем-то бот перестал видеть бусты как я понял походу сами разрабы NotCoin изменили ссылки на получение бустов

**Comment by shamhi** [comment]
> Вообщем-то бот перестал видеть бусты как я понял, на самом деле если зайти самому и кликнуть по бустам то пишет ошибку попробуйте позже, что-то на их стороне сломалось

да, скорее всего, статус код 5** это ошибка на стороне сервера

**Comment by shamhi** [comment]
что посоветуете, добавить настройку для отключения ежедневных бустов в таких ситуациях? или потерпите пока исправят?

**Comment by shamhi** [comment]
> настройку

Добавил, теперь можете указать в .env у полей ACTIVATE_DAILY_ENERGY и ACTIVATE_DAILY_TURBO =False так, как по умолчанию они True
