### ISSUE TITLE
Ошибка 502

### ISSUE THREAD

**Issue by Visualua** [shamhi/NotCoinBot#24]
10:02:24 | SUCCESS  | 166 - Mysession| Успешно сделал Click | Balance: 1026161 (+72) | Total Coins: 4043588
10:02:26 | INFO     | 596 - Mysession| Сплю 18 сек.
10:02:58 | ERROR    | 398 - Mysession| Неизвестный статус ответа: 502
10:03:14 | ERROR    | 398 - Mysession| Неизвестный статус ответа: 502
10:03:31 | ERROR    | 398 - Mysession| Неизвестный статус ответа: 502
10:03:50 | ERROR    | 398 - Mysession| Неизвестный статус ответа: 502
10:04:31 | SUCCESS  | 166 - Mysession| Успешно сделал Click | Balance: 1026821 (+660) | Total Coins: 4043660
10:04:35 | INFO     | 596 - Mysession| Сплю 17 сек.
10:04:55 | ERROR    | 398 - Mysession| Неизвестный статус ответа: 502

**Comment by shamhi** [comment]
Эта ошибка на стороне их сервера
