### ISSUE TITLE
Засыпает больше чем на 300 сек

### ISSUE THREAD

**Issue by PeLLmEn** [shamhi/NotCoinBot#3]
С последним обновлением заметил, что уходит в сон по достижении минимума монет и выходит через полчаса, хотя должен через 300сек, то есть через 5 мин.

UPD: проверил с конфигом на 30 сек - норм считает. Почему с 300 такие странности - хз
Посмотрел код, вроде никакого криминала в коммите, все указано верно.
90 сек тоже верно работает... Хз в чем прикол

Может сделаешь так, чтобы можно было отключить эту функцию при указании этого параметра в 0?

**Comment by shamhi** [comment]
> С последним обновлением заметил, что уходит в сон по достижении минимума монет и выходит через полчаса, хотя должен через 300сек, то есть через 5 мин.

странно, у меня все норм

**Comment by shamhi** [comment]
> Может сделаешь так, чтобы можно было отключить эту функцию при указании этого параметра в 0?

я сделал флаг для включения или отключения этой функции True | False

**Comment by PeLLmEn** [comment]
> я сделал флаг для включения или отключения этой функции True | False

Спасибо!

**Comment by PeLLmEn** [comment]
> предложи что еще добавить, а то у меня пока идей нет )

Счётчик того, сколько нафармил за час/24 часа, (ну или периоды какие-то, на твоё усмотрение) чтоб понимать, есть ли шанс в топ попасть) 

Ну можно допустим на час засыпать, собирать то что робот нафармил, фармить появившиеся монеты до 0 и снова на час засыпать. Хз, может так фарм будет быстрее.

Кстати, походу у меня косяк был с пакетами (что-то было обновлено, что-то конфликтовало по версиям) - переустановил termux, по новой поставил все пакеты и вроде работает без проблем. На термукс ещё тот геморрой ставить, например:
- pyqt5 только через pkg ставится, 
- pydantic только после установки rust, binutils, build-essential и только через phyton - m pip install...
- pminit ставится только после установки nodejs-lts

А с засыпанием не проверял сейчас - возможно после того как пакеты починил, все работает. Либо это из-за того что телефон с выключенным экраном лежит, хотя все разрешения есть и ограничения по использованию батареи сняты.

**Comment by VladislavShvetsov** [comment]
Сессию создал, но выдает ошибку: 
02:24:01 | WARNING  | 501 - azaza | Доступ к API запрещен: 403
02:24:01 | INFO     | 502 - azaza | Сплю 5 сек
02:24:07 | WARNING  | 501 - azaza | Доступ к API запрещен: 403
02:24:07 | INFO     | 502 - azaza | Сплю 5 сек

Куда копать?

**Comment by shamhi** [comment]
> > предложи что еще добавить, а то у меня пока идей нет )
> 
> Счётчик того, сколько нафармил за час/24 часа, (ну или периоды какие-то, на твоё усмотрение) чтоб понимать, есть ли шанс в топ попасть)
> 
> Можно прикрутить бота, как тут: https://github.com/Poryaei/NotCoin-Clicker Чтобы удалённо за всем следить, чтоб он ещё в конце дня присылал сколько на каком акке нафармил, ну и чтоб по командам это выдавал, и старт/стоп чтоб сделать можно было. Можно ещё сделать идентификации, когда ошибки идут - чтоб уведомлял, и если все норм пошло после ошибки - чтоб тоже отчитываться.
> 
> Еще можно, допустим, режим сделать - на час-два засыпать, собирать то что робот нафармил, фармить появившиеся монеты до 0 и снова на час-два засыпать. Хз, может так фарм будет быстрее. И вроде реализацию сбора монет от бота не видел нигде и иногда забываю собрать прежде чем бота запустить хД
> 
> Кстати, походу у меня косяк был с пакетами (что-то было обновлено, что-то конфликтовало по версиям) - переустановил termux, по новой поставил все пакеты и вроде работает без проблем. На termux ещё тот геморрой ставить, например:
> 
> * pyqt5 только через pkg ставится,
> * pydantic только после установки rust, binutils, build-essential и только через phyton - m pip install...
> * pminit ставится только после установки nodejs-lts
> 
> А с засыпанием не проверял сейчас - возможно после того как пакеты починил, все работает. Либо это из-за того что телефон с выключенным экраном лежит, хотя все разрешения есть и ограничения по использованию батареи сняты.
> 
> Кстати и без засыпания хорошо. До нуля доходит, потом поднимается до 3500 и снова снижается. Правда при выключенном экране время как-то странно считается.. Засыпает между кликами на 10..15 сек, а след действие только через 3-10мин причём рандомно, может и спустя 10..15сек, а может и 3..10мин... При включённом экране такого нет...


Одним словом - Termux ))
Спасибо за идеи, постараюсь сделать!

**Comment by psv-soledad** [comment]
У меня тоже ошибка 403.
Можно было бы брать прокси автоматом например с https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4&timeout=7000&country=all&ssl=all&anonymity=all чекать что они рабрчие и ходить через них переодически обновляя список

**Comment by PeLLmEn** [comment]
> Можно было бы брать прокси автоматом

Кстати идея хорошая, чтоб не запариваться

**Comment by VladislavShvetsov** [comment]
Днем бот работает нормально, а ночью всплывает  "Неизвестная ошибка при авторизации: A wait of 8296 seconds is required (caused by SendMessageRequest)", ну и время увеличивается

**Comment by PeLLmEn** [comment]
> Неизвестная ошибка при авторизации: A wait of 8296 seconds is required (caused by SendMessageRequest)"

У меня тоже самое сегодня было, в 6 утра 150раз отправил /start... И перезапуск не помогает - та же ошибка(

**Comment by shamhi** [comment]
прошу прощения, моя ошибка
это вам флудвейт дали за отправку /start боту, попробуйте обновить бота, исправил

**Comment by shamhi** [comment]
> И перезапуск не помогает - та же ошибка(

попробуй перезапустить, теперь должно работать и без отправки /start

**Comment by PeLLmEn** [comment]
> попробуй перезапустить, теперь должно работать и без отправки /start

Если работает без /start, то почему бы вообще его не писать? Кстати ща бот работает нормально

**Comment by shamhi** [comment]
> Если работает без /start, то почему бы вообще его не писать? Кстати ща бот работает нормально

ну смотри, в боте под кнопкой "Let's Mine (или как там)", которая отправляется после /start, лежит информация

_tgWebAppData=query_id%3FDAFtgD4WAgSSAG2APVZQR0Xv%26user%3D%257B%2522id%2522%253A5741838445%252C%2522first_name%2522%253A%2522Nick%2522%252C%2522last_name%2522%253A%2522Name%2522%252C%2522username%2522%253A%252Nick%2522%252C%2522language_code%2522%253A%2522en%2522%252C%2522allows_write_to_pm%2522%253Atrue%257D%26auth_date%3D170213123620%26hash%3D37d0d8673a7460d8f4975a17d41ys13ebe16a46c9085141af8s415b3674e4&tgWebAppVersion=7.0&tgWebAppPlatform=android&tgWebAppBotInline=1_

такого рода, и она (в частности hash) каждые 3 часа, и прошлая информация становится недействительной

именно для того, чтобы обновлять и получать эти данные, боту отправляется команда /start через какой-то промежуток времени

надеюсь понятно объяснил))

**Comment by PeLLmEn** [comment]
> именно для того, чтобы обновлять и получать эти данные, боту отправляется команда /start через какой-то промежуток времени
> 
> надеюсь понятно объяснил))

Это я понимаю. Но, например, бот, который я кидал выше, использует другой способ, так как не шлёт /start

**Comment by VladislavShvetsov** [comment]
> прошу прощения, моя ошибка это вам флудвейт дали за отправку /start боту, попробуйте обновить бота, исправил

Вроде стало работать стабильней, но в 3 часа ночи по мск выдает такую ошибку и лечится только запуском заново:
05:19:38 | WARNING  | 495 - azaza | Недействительные данные: 400
05:19:40 | DEBUG    | 498 - azaza | Генерация нового Auth токена
05:19:40 | SUCCESS  | 505 - azaza | Генерация завершена
05:19:42 | WARNING  | 495 - azaza | Недействительные данные: 400

**Comment by PeLLmEn** [comment]
> Вроде стало работать стабильней, но в 3 часа ночи по мск выдает такую ошибку и лечится только запуском заново:

Аналогичная ситуация

**Comment by PeLLmEn** [comment]
> на сервере днем все работает отлично, но вот ночью выдает 403

Может тогда при ней сделать полный перезапуск программы? Просто это помогает прям сразу. Как начинают лететь warning - на третий-четвёртым раз делать просто перезапуск программы и поидее должно помочь

**Comment by shamhi** [comment]
> Может тогда при ней сделать полный перезапуск программы?

при перезапуске ничего, кроме auth токена не меняется
добавил код который генерирует новый auth токен при ошибке 403, надеюсь поможет

**Comment by PeLLmEn** [comment]
> надеюсь поможет

Теперь спустя время возникает 400 ошибка и фиксится тоже только перезапуск ом. Пару дней проверял - все время одно и то же спустя время
![IMG_20240127_092725](https://github.com/shamhi/NotCoinBot/assets/36919324/0ec39a34-68a0-4cce-83d6-f120e7f50897)

**Comment by AcrimoniousLow74** [comment]
> предложи что еще добавить, а то у меня пока идей нет )
1. бот когда появляются ежедневные бусты full energy - делает клик и потом снова активирует этот же буст на полную энергию. хотя мог бы сначала прокликать всё что есть и потом только вновь активировать бус.
2. добавить рандомное число между min и max. параметру SLEEP_BY_MIN_COINS_TIME

**Comment by shamhi** [comment]
Бот обновлен!!!
