### ISSUE TITLE
pydantic_settings.sources.SettingsError: error parsing value for field "SLEEP_BETWEEN_CLICK" from source "DotEnvSettingsSource"

### ISSUE THREAD

**Issue by codeCEO7** [shamhi/NotCoinBot#35]
Вызывается ошибка при запуске

![изображение](https://github.com/shamhi/NotCoinBot/assets/103880331/a783f50f-b8b2-4a81-8cdd-3c467b69524a)

**Comment by shamhi** [comment]
your settings are invalid
look in the [config](https://github.com/shamhi/NotCoinBot/blob/main/config/config.py) how the settings are set, if this is list[int] then you need to set values separated by commas (e. g. 10,25)
