### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by Lunoul** [shamhi/NotCoinBot#36]
![изображение](https://github.com/shamhi/NotCoinBot/assets/63908666/a8c29041-e3e6-46f9-85c3-56317da37237)
Хз, влияет ли это на что-то, но высвечивается.

**Comment by shamhi** [comment]
После перезапуска не исправляется?

**Comment by Lunoul** [comment]
Не исправляется, но сам варнинг никак не влияет на процесс кликера, так что просто странный прикольдес.

**Comment by shamhi** [comment]
аа, это у них проблемы были еще вчера, даже в приложении бусты энергии не брались
возможно связано с этим
