### ISSUE TITLE
Ошибка 404 при активации буста

### ISSUE THREAD

**Issue by GmeX1** [shamhi/NotCoinBot#43]
Привет, бот отличный, но у него не получается активировать бусты. Вот лог:
```
22:26:22 | SUCCESS  | 168 - Test | Успешно сделал Click | Balance: 8307 (+135) | Total Coins: 8115
22:26:23 | INFO     | 577 - Test | Сплю 13 перед активацией ежедневного Full Energy
22:26:36 | ERROR    | 270 - Test | Неизвестный ответ при активации Task 2: {"ok":false,"data":{"message":"Daily tasks are not supported","error":"HttpException","statusCode":404}}
```
Edit: Это происходит с любым бустом

**Comment by Visualua** [comment]
Бусты уже выключены в самой игре .env файле поменяй эти две строки на фолс:

ACTIVATE_DAILY_ENERGY=**False**
ACTIVATE_DAILY_TURBO=**False**

**Comment by GmeX1** [comment]
> Бусты уже выключены в самой игре .env файле поменяй эти две строки на фолс:
Буквально вчера ещё утром всё включено было, зашёл в приложение, действительно выключили бусты 0_о
Никто не знает, вернут бусты или нет?
