### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by soshin1337** [shamhi/NotCoinBot#5]
![image](https://github.com/shamhi/NotCoinBot/assets/15040527/47b7614e-c978-42a1-9cca-1fb6f2366e01)
Нет задержки между получением данных профиля.

![image](https://github.com/shamhi/NotCoinBot/assets/15040527/eff65658-1adc-4f9d-9691-83f47930702d)
Так же предлагаю при возникновении такой ошибки ребутать скрипт, либо исправить получение токена.

**Comment by shamhi** [comment]
в данном случае, проблемы у тебя с сетью
добавил задержку в 2 секунды и вывод статуса запроса [здесь (https://github.com/shamhi/NotCoinBot/commit/ea08db6a3bac69873a246957444b4b3b7bd15d31)
