### ISSUE TITLE
Доступ к API запрещен: 403

### ISSUE THREAD

**Issue by psv-soledad** [shamhi/NotCoinBot#6]
Как решать такую проблему?

```
02:24:01 | WARNING | 501 - a1 | Доступ к API запрещен: 403
02:24:01 | INFO | 502 - a1 | Сплю 5 сек
02:24:07 | WARNING | 501 - a1 | Доступ к API запрещен: 403
02:24:07 | INFO | 502 - a1 | Сплю 5 сек
```

Видел сообщение про впн но это не так просто сделать на vds
если беру прокси получаю ошибку типа 

```
Server closed the connection: 0 bytes read on a total of 8 expected bytes
Server closed the connection: 0 bytes read on a total of 8 expected bytes
Server closed the connection: 0 bytes read on a total of 8 expected bytes
Server closed the connection: 0 bytes read on a total of 8 expected bytes
Server closed the connection: 0 bytes read on a total of 8 expected bytes
Server closed the connection: 0 bytes read on a total of 8 expected bytes
```

**Comment by shamhi** [comment]
> если беру прокси получаю ошибку типа
где вы указывали прокси? в файле или при создании сессии?

**Comment by psv-soledad** [comment]
Поэкспериментировал с разными проксями, как итог ошибка выше была из-за плохой прокси скорее всего с хорошей сразу летят 403, с не очень бывает так 
<img width="866" alt="image" src="https://github.com/shamhi/NotCoinBot/assets/5561009/a588a68b-e4ed-46ba-8e53-0ac96553cb70">
Но как итог всегда 403... хотя с другими кликерами работает =(

**Comment by j0k3r4132** [comment]
Фармил полдня с ru ip - было все ок, Затем запустил на vps с usa ip и сразу же словил 403. После этого 403 и на ru ip.
